### ISSUE TITLE
Import flybrains creates flybrain-data folder im home directory

### ISSUE THREAD

**Issue by unidesigner** [navis-org/navis-flybrains#10]
Would it be possible to prevent creating this folder by default, even without an environmental variable set?

**Comment by schlegelp** [comment]
Already changed that behavior with 496fe3b92dc4499b836298e00d9b6286ae305bc0. It's just not released yet.

**Comment by unidesigner** [comment]
Ah, ok. Great.

**Comment by schlegelp** [comment]
Released with 0.2.3
